version: '2'
services:
  server:
    container_name: kobin_server
    build:
      context: ./server
    environment:
      - KOBIN_TODO_ENV=docker
      - KOBIN_TODO_SECRET_KEY=secretkey

      - KOBIN_TODO_REDIS_HOST=redis
      - KOBIN_TODO_REDIS_PORT=6379
      - KOBIN_TODO_REDIS_DB=0
      - KOBIN_TODO_REDIS_PASSWORD=password

      - KOBIN_TODO_DATABASE_HOST=postgres
      - KOBIN_TODO_DATABASE_USER=kobin
      - KOBIN_TODO_DATABASE_PASSWORD=password
      - KOBIN_TODO_DATABASE_NAME=kobintodo

      - KOBIN_TODO_GITHUB_CLIENT_ID
      - KOBIN_TODO_GITHUB_CLIENT_SECRET
    links:
      - postgres
      - redis

  front:
    container_name: kobin_front
    build:
      context: ./front
    volumes:
      - ./front/public:/usr/src/public
      - /usr/src/public

  nginx:
    image: nginx
    container_name: kobin_nginx
    volumes:
      - ./nginx/kobin-todo.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    volumes_from:
      - front
    links:
      - server

  postgres:
    image: postgres:latest
    container_name: kobin_postgres
    environment:
      - POSTGRES_USER=kobin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=kobintodo
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: kobin_redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass password
