version: '2'
services:
  server:
    container_name: kobin_server
    build:
      context: ./server
    environment:
      - KOBIN_TODO_ENV=docker
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=kobin
      - POSTGRES_NAME=kobintodo

      - SECRET_KEY
      - REDIS_PASSWORD
      - POSTGRES_PASSWORD
      - KOBIN_TODO_GITHUB_CLIENT_ID
      - KOBIN_TODO_GITHUB_CLIENT_SECRET
    links:
      - postgres
      - redis
    ports:
      - "8080:80"
    volumes_from:
      - front
    command: gunicorn -w 1 -b :80 --reload --log-level debug gunicorn_entrypoint:app

  front:
    container_name: kobin_front
    build:
      context: ./front
    volumes:
      - ./front/public:/usr/src/public
      - /usr/src/public

  postgres:
    image: postgres:latest
    container_name: kobin_postgres
    environment:
      - POSTGRES_USER=kobin
      - POSTGRES_DB=kobintodo
      - POSTGRES_PASSWORD
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: kobin_redis
    environment:
      - REDIS_PASSWORD
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
